import "./global.css";
import { Metadata } from "next";
import Link from "next/link";
/* export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
} */

export const metadata: Metadata = {
  title: {
    default: "Aprendiendo Next.js",
    absolute: "",
    template: "%s-Aprendiendo Next.js"
  }
}  
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header>
        <h2>Cabecera de la App</h2>
        <nav>
          <ul>
            <Link href="/">Home</Link>
            <br />
            <Link href="/acerca">Acerca</Link>
            <br />
            <Link href="/contacto">Contacto</Link>
            <br />
            <Link href="/blog">Blog</Link>
            <br />
            <Link href="/productos">Productos</Link>
            <br />
            <Link href="/login">Login</Link>
            <br />
            <Link href="/registro">Registro</Link>
            <br />
            <Link href="/password">Recuperar password</Link>
          </ul>
        </nav>
      </header>
      <main>{children}</main>
      <footer>Pie de pagina</footer>
      </body>
    </html>
  )
}
