import "./global.css";
import { Metadata } from "next";
/* export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
} */

export const metadata: Metadata = {
  title: {
    default: "Aprendiendo Next.js",
    absolute: "",
    template: "%s-Aprendiendo Next.js"
  }
}  
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header>Cabecera de la App</header>
      <main>{children}</main>
      <footer>Pie de pagina</footer>
      </body>
    </html>
  )
}
